// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDByvQXSVkU1pl4mMKr3oSHDxM3Ilf69Is',
    appId: '1:930075888107:web:4d6ed253b0fffc3c11f1ae',
    messagingSenderId: '930075888107',
    projectId: 'notes-app-with-getx-6bc76',
    authDomain: 'notes-app-with-getx-6bc76.firebaseapp.com',
    storageBucket: 'notes-app-with-getx-6bc76.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBWXlqbXQgB3E8WaR7imoXnu58WfKoP1Q',
    appId: '1:930075888107:ios:6a0e827cdb47ee9111f1ae',
    messagingSenderId: '930075888107',
    projectId: 'notes-app-with-getx-6bc76',
    storageBucket: 'notes-app-with-getx-6bc76.firebasestorage.app',
    iosBundleId: 'com.example.notesAppWithGetx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDByvQXSVkU1pl4mMKr3oSHDxM3Ilf69Is',
    appId: '1:930075888107:web:cb3c501644e7a91b11f1ae',
    messagingSenderId: '930075888107',
    projectId: 'notes-app-with-getx-6bc76',
    authDomain: 'notes-app-with-getx-6bc76.firebaseapp.com',
    storageBucket: 'notes-app-with-getx-6bc76.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBWXlqbXQgB3E8WaR7imoXnu58WfKoP1Q',
    appId: '1:930075888107:ios:6a0e827cdb47ee9111f1ae',
    messagingSenderId: '930075888107',
    projectId: 'notes-app-with-getx-6bc76',
    storageBucket: 'notes-app-with-getx-6bc76.firebasestorage.app',
    iosBundleId: 'com.example.notesAppWithGetx',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVX-nWJikRzfwIZV79LrsHGD_sPbv2rg4',
    appId: '1:930075888107:android:1005670904ab725e11f1ae',
    messagingSenderId: '930075888107',
    projectId: 'notes-app-with-getx-6bc76',
    storageBucket: 'notes-app-with-getx-6bc76.firebasestorage.app',
  );

}